### PR TITLE
#27 Fix

### LINKED ISSUE #15: Dont Change File Permissions on Clean
Noticed when I run clean I'll often see files listed as modified even though there is no content changes. Dug a bit deeper and ran a patch and can see lines like this

`mode change 100755 => 100644 src/main/default/classes/SomeClass.cls-meta.xml`

Would be nice if we could avoid this, although this could just be an issue on the first sync after which everything ends up with the default file permissions sfdx retrieve gives them.

### PR DESCRIPTION
**Pull request by ChuckJonas**
- upgrading the sfdx bootstrap to latest
- changing logic to mark EVERYTHING instead of unlinking non-metadata files

I also think this should resolve #15

### CODE REVIEW

File: src/commands/force/source/clean.ts [hunk 1]
```diff
@@ -160,28 +132,28 @@ function markContents(targetDir: string, ignore: Ignore) {
         if (stat.isDirectory()) {
           markContents(filePath, ignore);
         } else {
-
           if (!ignore.ignores(filePath)) {
-            if (!filePath.endsWith('-meta.xml')) {
```
Comment (ChuckJonas) [inline src/commands/force/source/clean.ts:165]: @ben-faber-ccc  This is basically the change...  We used to delete files except for the `-meta.xml`.  

I think the delete marker was added later. I'm not sure why we didn't just make it mark everything at that point.
